server:
    port: 8082

spring:
    application:
        name: auth-gateway
    security:
        jwt:
            secretKey: ${JWT_SECRET_KEY}
            expiration: 86400000
            refresh-token:
                expiration: 2592000000
            cookie-name: auth-token
    datasource:
        url: jdbc:postgresql://localhost:5432/pruebas
        username: usuariopruebas
        password: 1234
        driver-class-name: org.postgresql.Driver

    jpa:
        database: POSTGRESQL
        show-sql: false
        hibernate:
            ddl-auto: update

springdoc:
    api-docs:
        enabled: false
    swagger-ui:
        enabled: false
    info:
        title: "Auth Gateway API"
        description: "Authentication and Authorization Gateway"
        version: "1.0.0"
